name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # This tells the robot to work every time you save to 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # This tells it to upload everything in your folder
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
